### ISSUE TITLE
Update and add interfaces for the puts based on PRIF version 0.4

### ISSUE THREAD

**Issue by ktras** [BerkeleyLab/caffeine#116] opened 2024-06-26 17:32 UTC
- [ ] `put`
- [ ] `put_indirect`
- [ ] `put_with_notify`
- [ ] `put_indirect_with_notify`
- [ ] `put_with_notify_indirect`
- [ ] `put_indirect_with_notify_indirect`
- [ ] `put_strided`
- [ ] `put_strided_indirect`
- [ ] `put_strided_with_notify`
- [ ] `put_strided_indirect_with_notify`
- [ ] `put_strided_with_notify_indirect`
- [ ] `put_strided_indirect_with_notify_indirect`

**Comment by bonachea** [comment] 2024-07-26 01:37
duplicate of #119

**Closed by bonachea** 2024-07-26 01:37 UTC
